"""Add encryption version to messages

Revision ID: 06b212308517
Revises: 348179efeeeb
Create Date: 2025-11-20 16:52:50.766317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b212308517'
down_revision: Union[str, None] = '348179efeeeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('encryption_version', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'encryption_version')
    # ### end Alembic commands ###
